services:

  anisette:
    image: dadoum/anisette-v3-server
    container_name: anisette
    restart: always
    ports:
      - "6969:6969"
    volumes:
      - anisette-v3_data:/home/Alcoholic/.config/anisette-v3
    networks:
      - mh-network

  aura-worker:
    build: .
    container_name: macless-worker
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - anisette
    environment:
      - ANISETTE_URL=http://anisette:6969

      - APPLE_ID=seu_email@apple.com
      - APPLE_PWD=sua_senha
    volumes:
      - worker_data:/root/.config/findmy
    networks:
      - mh-network

volumes:
  anisette-v3_data:
  worker_data:

networks:
  mh-network:
    driver: bridge